import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'AI Book Chapters',
      link: {type: 'generated-index', title: 'All Chapters'},
      items: [{type: 'autogenerated', dirName: '.'}],
    },
  ],
};

export default sidebars;
